### ISSUE TITLE
'No SD card'

### ISSUE THREAD

**Issue by adrianblakey** [sbcshop/MicroSD-Breakout#1]
Any ideas what's going on?

MicroPython 1.23
Pi Pico W
There's a 128GB SD card in the device that's been formatted as FAT32.

The SD reader is connected to pins 4, 5, 6, 7 (gp2, gp3, gp4, gp5)

Note: the call to self.cmd(0, 0, 0x95) returns -1

Traceback (most recent call last):
  File "<stdin>", line 44, in <module>
  File "<stdin>", line 23, in sdtest
  File "sdcard.py", line 55, in __init__
  File "sdcard.py", line 83, in init_card
OSError: no SD card

```
18 def sdtest(data):
    print('sdtest')
    spi=SPI(0, sck=Pin(2), mosi=Pin(3), miso=Pin(4))
    cs = Pin(5, mode=Pin.OUT, value=1)  
    
23    sd=sdcard.SDCard(spi, Pin(7))
```

```
67     def init_card(self):
        # init CS pin
        self.cs.init(self.cs.OUT, value=1)

        # init SPI bus; use low data rate for initialisation
        self.init_spi(100000)

        # clock card at least 100 cycles with cs high
        for i in range(16):
            self.spi.write(b"\xff")

        # CMD0: init card; should return _R1_IDLE_STATE (allow 5 attempts)
        for _ in range(5):
            if self.cmd(0, 0, 0x95) == _R1_IDLE_STATE:
                break
        else:
83            raise OSError("no SD card")
```

**Comment by sbcshop3** [comment]
Follow below code changes=>
```
def sdtest(data):
    print('sdtest')
    spi=SPI(0, sck=Pin(2), mosi=Pin(3), miso=Pin(4))
    sd=sdcard.SDCard(spi, Pin(5))
```
